### ISSUE TITLE
I want to disable contextmenu (rightclick) on pdf files

### ISSUE THREAD

**Issue by revl94** [Marcelh1983/document-viewer#1]
I really need to disabled right click, but the library dont let me!

**Comment by Marcelh1983** [comment]
I assume you are using the google or office viewer. Both are rendered in an iframe. Unfortunately there is no way to control the iframe.

**Comment by revl94** [comment]
Im using pdf viwer, im want to disabled right click or "preventDefault()" but all i tried didnt work, i dont want to show the contexmenu, couldnt make it with that library?

**Comment by Marcelh1983** [comment]
Only thing the pdf viewer does is wrapping your url in an object/embed tag (if you are using this mode only, you might just write it yourself instead of using this library, sanitize the url and place it in a embed tag). This library doesn't do anything to prevent you from writing code to disable a right click. Please check stackoverflow to check how to disable right click in a embed tag. It's not something I plan to add to library. 

https://stackoverflow.com/questions/63521705/how-to-disable-right-click-on-embed-tag
