### ISSUE TITLE
Please add the functionality of hiding End div ( downloading and other functionality option)

### ISSUE THREAD

**Issue by mohitmunjal2801** [Marcelh1983/document-viewer#21]

**Comment by Marcelh1983** [comment]
Hi @mohitmunjal2801, I added functionality to 'hide' some buttons, by overlaying things in the iframe. I regret doing this, because it's not a real solution and if google changes something in their layout, it doesn't work anymore... and.. I cost me time and I don't use this functionality myself. 

If you want this functionality I you could get some inspiration from where where I use disableContent in ```document-viewer.component.html``` If you think it's something that other users would like to have too then you're very welcome to do a pull request.
