### ISSUE TITLE
Doc display blank some time

### ISSUE THREAD

**Issue by vickyChauhan12** [Marcelh1983/document-viewer#39]
Hi , I have integrate the document viewer it's work fine. But some time it doesn't display anything as show in below screenshot  
https://prnt.sc/26wroe2
Kindly help me to resolve this issue
Thanks

**Comment by vickyChauhan12** [comment]
Anyone kindly reply on the above  issue

**Comment by adv-gustavomorinaga** [comment]
> Hi , I have integrate the document viewer it's work fine. But some time it doesn't display anything as show in below screenshot https://prnt.sc/26wroe2 Kindly help me to resolve this issue Thanks

Same here, when I enter on the component with doc viewer, doesn't display anything... But when I refresh the page, works fine.

**Comment by Marcelh1983** [comment]
Is this using the google viewer? It's a known issue that the page sometimes opens blank the first time. Therefor I added the googleCheckContentLoaded (default true) which refreshes the iframe until the document is loaded. You could try to play with googleCheckInterval  option to set the number of milliseconds greater or smaller that the default (3000). I you could reproduce this in a stackblitz I could have a look.

**Comment by wilianx7** [comment]
I managed to solve the problem as follows:

* I go through the iFrames contained in the ```NgxDocViewerComponent``` within an interval and, at each iteration, I check the existence of a property in the iFrame, the "contentDocument";
* I noticed that when the iFrame is loaded correctly this property is null, otherwise it has value;
* My interval is 1 second and every time the iFrame doesn't load correctly, I request it to reload through the ```reloadIFrame``` method available in ```NgxDocViewerComponent```.

The implementation looked like this:

![image](https://user-images.githubusercontent.com/42422976/161998853-5a5090e9-4981-4e6a-8aa3-1759bd0573f4.png)

**obs**: I'm using Google viewer.

**Comment by maniyahasu** [comment]
Hi @wilianx7 ,

Actually, I am trying to view .pdf and .docx files using this plugin with base64 encoded data but some how I unable to do so. 
Could you please share Stackblitz example if you have any OR can you please assist me how I can render pdf/docx with base64 encoded data ?

Appreciate your help :)

Thanks

**Comment by vikasgunjeti** [comment]
Hi All,

I am also facing the same issue with using google viewer. anyone solve this issue?.

If Yes can you please tell us the solution.

Thank you,

Vikas
