### ISSUE TITLE
disableContent not working properly

### ISSUE THREAD

**Issue by jsofii** [Marcelh1983/document-viewer#9]
disableContent: popout-hide 
When I use this input, it overlays the popout. But it only hides one part of the icon, so the popout button is not hidden properly.

**Comment by Marcelh1983** [comment]
Hi @jsofii. I actually regret adding this functionaly, because it's not a real solution and if google changes something in their layout, it doesn't work anymore... and it cost me time and I don't use this functionality myself. So if this needs to be fixed I'd love to receive a pull-request with a fix.

**Comment by Marcelh1983** [comment]
I'm linking this issue to #24 and close this one.
